// AUTO-GENERATED by packages/contracts/script/export-artifacts.mjs — do not edit.

export const ChatLogAbi = [
  {
    "type": "function",
    "name": "commit",
    "inputs": [
      {
        "name": "contentHash",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "ref",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "MessageCommitted",
    "inputs": [
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "contentHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "timestamp",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "ref",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  }
] as const;

export const ChatLogBytecode = "0x6080604052348015600e575f5ffd5b5061016f8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610029575f3560e01c8063604d9c011461002d575b5f5ffd5b61004061003b36600461008d565b610042565b005b82336001600160a01b03167f59d85dd625cb33ddadafd34ee740616da0b6570782b86db0c02c550b0fa7a85642858560405161008093929190610104565b60405180910390a3505050565b5f5f5f6040848603121561009f575f5ffd5b83359250602084013567ffffffffffffffff8111156100bc575f5ffd5b8401601f810186136100cc575f5ffd5b803567ffffffffffffffff8111156100e2575f5ffd5b8660208284010111156100f3575f5ffd5b939660209190910195509293505050565b83815260406020820152816040820152818360608301375f818301606090810191909152601f909201601f191601019291505056fea2646970667358221220de3ad1aa5a702eb8e0a80a44ba894bac11d80bcc0528c43d9091e395843a6ba264736f6c634300081c0033" as const;

export const ChatLogDeployedBytecode = "0x608060405234801561000f575f5ffd5b5060043610610029575f3560e01c8063604d9c011461002d575b5f5ffd5b61004061003b36600461008d565b610042565b005b82336001600160a01b03167f59d85dd625cb33ddadafd34ee740616da0b6570782b86db0c02c550b0fa7a85642858560405161008093929190610104565b60405180910390a3505050565b5f5f5f6040848603121561009f575f5ffd5b83359250602084013567ffffffffffffffff8111156100bc575f5ffd5b8401601f810186136100cc575f5ffd5b803567ffffffffffffffff8111156100e2575f5ffd5b8660208284010111156100f3575f5ffd5b939660209190910195509293505050565b83815260406020820152816040820152818360608301375f818301606090810191909152601f909201601f191601019291505056fea2646970667358221220de3ad1aa5a702eb8e0a80a44ba894bac11d80bcc0528c43d9091e395843a6ba264736f6c634300081c0033" as const;
