// AUTO-GENERATED by packages/contracts/script/export-artifacts.mjs — do not edit.

export * from "./NexusERC20";
export * from "./NexusERC721";
export * from "./NexusERC1155";
export * from "./ChatLog";
export * from "./EntryPoint";
export * from "./SimpleAccountFactory";
export * from "./SimpleAccount";
export * from "./VerifyingPaymaster";

import { NexusERC20Abi, NexusERC20Bytecode } from "./NexusERC20";
import { NexusERC721Abi, NexusERC721Bytecode } from "./NexusERC721";
import { NexusERC1155Abi, NexusERC1155Bytecode } from "./NexusERC1155";
import { ChatLogAbi, ChatLogBytecode } from "./ChatLog";
import { EntryPointAbi, EntryPointBytecode } from "./EntryPoint";
import { SimpleAccountFactoryAbi, SimpleAccountFactoryBytecode } from "./SimpleAccountFactory";
import { SimpleAccountAbi, SimpleAccountBytecode } from "./SimpleAccount";
import { VerifyingPaymasterAbi, VerifyingPaymasterBytecode } from "./VerifyingPaymaster";

export const contractArtifacts = {
  NexusERC20: { abi: NexusERC20Abi, bytecode: NexusERC20Bytecode },
  NexusERC721: { abi: NexusERC721Abi, bytecode: NexusERC721Bytecode },
  NexusERC1155: { abi: NexusERC1155Abi, bytecode: NexusERC1155Bytecode },
  ChatLog: { abi: ChatLogAbi, bytecode: ChatLogBytecode },
  EntryPoint: { abi: EntryPointAbi, bytecode: EntryPointBytecode },
  SimpleAccountFactory: { abi: SimpleAccountFactoryAbi, bytecode: SimpleAccountFactoryBytecode },
  SimpleAccount: { abi: SimpleAccountAbi, bytecode: SimpleAccountBytecode },
  VerifyingPaymaster: { abi: VerifyingPaymasterAbi, bytecode: VerifyingPaymasterBytecode },
} as const;

export type ContractName = keyof typeof contractArtifacts;
