// AUTO-GENERATED by packages/contracts/script/export-artifacts.mjs — do not edit.

export * from "./NexusERC20.js";
export * from "./NexusERC721.js";
export * from "./NexusERC1155.js";

import { NexusERC20Abi, NexusERC20Bytecode } from "./NexusERC20.js";
import { NexusERC721Abi, NexusERC721Bytecode } from "./NexusERC721.js";
import { NexusERC1155Abi, NexusERC1155Bytecode } from "./NexusERC1155.js";

export const contractArtifacts = {
  NexusERC20: { abi: NexusERC20Abi, bytecode: NexusERC20Bytecode },
  NexusERC721: { abi: NexusERC721Abi, bytecode: NexusERC721Bytecode },
  NexusERC1155: { abi: NexusERC1155Abi, bytecode: NexusERC1155Bytecode },
} as const;

export type ContractName = keyof typeof contractArtifacts;
