// Deploy-data builder — turns a validated launchpad request into the unsigned
// contract-creation calldata (bytecode + ABI-encoded constructor args) using the
// COMMITTED token-template artifacts (#11) and viem (SPEC §6/§8.5, AGENT.md §7).
//
// PURE + server/client-safe (viem only, no DB). Solidity is NEVER compiled at
// request time — we encode against the precompiled bytecode. Amounts are bigint
// in memory (initialSupply is a wei string parsed here, never `Number()`-ed).
import { encodeDeployData, getAddress } from 'viem';
import type { Hex } from 'viem';
import {
  NexusERC20Abi,
  NexusERC20Bytecode,
  NexusERC721Abi,
  NexusERC721Bytecode,
  NexusERC1155Abi,
  NexusERC1155Bytecode,
} from '@nexus/types';
import type { DeployRequest } from './schema';

/** The generated bytecode strings are typed as `string`; they are 0x-hex. */
const BYTECODE: Record<ContractName, Hex> = {
  NexusERC20: NexusERC20Bytecode as Hex,
  NexusERC721: NexusERC721Bytecode as Hex,
  NexusERC1155: NexusERC1155Bytecode as Hex,
};

const ABI = {
  NexusERC20: NexusERC20Abi,
  NexusERC721: NexusERC721Abi,
  NexusERC1155: NexusERC1155Abi,
} as const;

export type ContractName = 'NexusERC20' | 'NexusERC721' | 'NexusERC1155';

/** Map a token standard to its committed template contract name. */
export function contractNameForStandard(standard: DeployRequest['standard']): ContractName {
  switch (standard) {
    case 'ERC20':
      return 'NexusERC20';
    case 'ERC721':
      return 'NexusERC721';
    case 'ERC1155':
      return 'NexusERC1155';
  }
}

/** Result of building the unsigned deploy calldata. */
export interface DeployDataResult {
  contractName: ContractName;
  /** bytecode + ABI-encoded constructor args — the tx `data` for a create. */
  data: Hex;
}

/**
 * Build the contract-creation calldata for a launchpad request. `owner` is the
 * deployer's public address (the vault keypair the client will sign with); it is
 * the constructor `owner` that receives roles + the ERC-20 initial supply.
 */
export function buildDeployData(request: DeployRequest, owner: string): DeployDataResult {
  const ownerAddress = getAddress(owner);
  const contractName = contractNameForStandard(request.standard);

  switch (request.standard) {
    case 'ERC20': {
      const { name, symbol, initialSupply, features } = request;
      const data = encodeDeployData({
        abi: ABI.NexusERC20,
        bytecode: BYTECODE.NexusERC20,
        args: [
          name,
          symbol,
          BigInt(initialSupply),
          ownerAddress,
          {
            mintable: features.mintable,
            burnable: features.burnable,
            pausable: features.pausable,
            permit: features.permit,
          },
        ],
      });
      return { contractName, data };
    }
    case 'ERC721': {
      const { name, symbol, baseUri, features } = request;
      const data = encodeDeployData({
        abi: ABI.NexusERC721,
        bytecode: BYTECODE.NexusERC721,
        args: [
          name,
          symbol,
          baseUri ?? '',
          ownerAddress,
          {
            mintable: features.mintable,
            burnable: features.burnable,
            pausable: features.pausable,
          },
        ],
      });
      return { contractName, data };
    }
    case 'ERC1155': {
      const { baseUri, features } = request;
      const data = encodeDeployData({
        abi: ABI.NexusERC1155,
        bytecode: BYTECODE.NexusERC1155,
        args: [
          baseUri ?? '',
          ownerAddress,
          {
            mintable: features.mintable,
            burnable: features.burnable,
            pausable: features.pausable,
            supply: features.supply,
          },
        ],
      });
      return { contractName, data };
    }
  }
}

/** ABI for a contract name (for decode round-trips / reads). */
export function abiFor(contractName: ContractName) {
  return ABI[contractName];
}

/** Committed bytecode for a contract name. */
export function bytecodeFor(contractName: ContractName): Hex {
  return BYTECODE[contractName];
}
